$color = rgba(26, 21, 21, 1)
$inner_color = rgba(26, 21, 21, 0.66)
$outer_color = rgba(123, 61, 121, 1)
$font_color = rgba(255, 233, 199, 1)
$placeholder_color = rgba(255, 233, 199, 0.7)
$check_color = rgba(117, 109, 148, 1)

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = VictorMono Nerd Font
    font_color = $font_color

    placeholder_text = enter password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 12
    shadow_passes = 2
    fade_on_empty = false
}

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#
