-- Generated by scripts/hypr2lua.
-- Source: omarchy-biscuit-de-mar-dark-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(E39C45)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)" },
  angle = 35,
}
local inactiveBorderColor = "rgba(725a5acc)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    blur = {
      size = 4,
      passes = 3,
    },
  },
})

hl.layer_rule({
  match = { namespace = "waybar" },
  blur  = true,
})

hl.layer_rule({
  match = { namespace = "walker" },
  blur  = true,
})

hl.animation({ leaf = "workspaces", enabled = true, speed = 6, curve = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 6, curve = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6, curve = "easeOutQuint", style = "slide" })
